### ISSUE TITLE
There isn't enough contrast for the headers text

### ISSUE THREAD

**Issue by Sophia-Villamayor** [Sophia-Villamayor/kraken-good-accessibility#3]
@JessJodoin

I'm not sure as to which tag I need to focus on, to make the contrast more visible
<img width="505" alt="Screen Shot 2020-09-28 at 11 59 17 AM" src="https://user-images.githubusercontent.com/54897840/94466617-beebaf00-018f-11eb-87e7-331347314919.png">

**Comment by JessJodoin** [comment]
Try adding this to your `<header>`
```
header {
  background-color: #1e7c74;
  background-image: url("../images/anchors.svg");
  color: #fff;
  font-size: 1.125rem;
  font-style: normal;
  font-weight: normal;
  padding: 1rem;
}
```

**Comment by Sophia-Villamayor** [comment]
@JessJodoin 
Sorry I didn't see there was a notification. Unfortunately that didn't work :((
